### ISSUE TITLE
米6 MUI9开发版无法安装

### ISSUE THREAD

**Issue by youareumasou** [QiuChenly/iComic#1]
最新版本无法安装，显示原因：其他原因。

**Comment by QiuChenly** [comment]
你好,请尝试检查步骤:
1.Android 系统是否是 4.4 或以上
2.下载 adb 工具包在电脑上,安装 安卓手机adb 驱动后使用 cmd 命令行执行以下指令:
adb install apk文件全路径(注意空格)
并将电脑 cmd 窗口返回的截图传给我检查原因,谢谢!

**Comment by makishi-youko** [comment]
感觉很不错！(^o^;

**Comment by youareumasou** [comment]
哦 你好，最新版的可以安装正常使用。ADB可以把那个版本装上，但是打不开可我不会上图。

**Comment by QiuChenly** [comment]
那你实属弟中弟嗷,无法安装的那个 APK 包可能是我本地编译打包问题,没问题就行.最低兼容 4.4-9.0.
